#!/usr/bin/env julia

import REPL: REPLCompletions

const scope = ""
const name = ""

open("$(scope)_$(name).snippets", "w") do f
    println(f, "# This file was generated by `$(basename(Base.source_path()))`")
    println(f, "# using Julia $VERSION")
    println(f)
    for (keyword, unicode) in sort!(collect(
            Iterators.flatten((REPLCompletions.latex_symbols,
                               REPLCompletions.emoji_symbols))), by=x -> x[2])
        println(f, "snippet ", keyword, " ", unicode)
        println(f, "\t", unicode)
    end
end
